name: Test

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version: ['8.1']
                directory:
                    - '.'

        name: Test - ${{ matrix.directory }}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -
                run: composer install --ansi
                working-directory: ${{ matrix.directory }}/app

            -
                run: app/vendor/bin/rector process --ansi
                working-directory: ${{ matrix.directory }}